In [68]:
%run Metodos_Propios.ipynb

In [30]:
import pandas as pd
import glob
#import ipynb.fs.full.Funciones_Auxiliares as fa
pd.set_option('display.max_rows', 500)

In [13]:
#Definción de variables
df_id = pd.DataFrame()
df_info = pd.DataFrame()
df_tweets = pd.DataFrame()
fact_following = pd.DataFrame()

# Lectura Tweets 2020 - El Corte Inglés

In [69]:
def read_all_Tweets():
    all_files = glob.glob('info_tweets_el_cor*.csv')
    files =[]
    df = creacionDataFrame()
    for file in all_files:
        tweets = readCSV(df_id,file)
        files.append(tweets)

    df_tweets = pd.concat(files)
    return df_tweets

tweets = tweets = read_all_Tweets()
tweets.head(10)

,id,date,username,text,geo
0,1255640710847401985,2020-04-29 23:30:48+00:00,camilaperezv13,yo nunca lo he hecho en el corte inglés JAJAJA...,NaN
1,1255636516111560706,2020-04-29 23:14:08+00:00,VicenteToms14,O q de n sair a rua bb n haha eu aguento me na...,NaN
2,1255633358748553216,2020-04-29 23:01:35+00:00,Marina47083380,@pablocasado_ @PSOE @podemos @sanchezcastejon ...,NaN
3,1255632958758752257,2020-04-29 23:00:00+00:00,ainderlab,Lo #RecomiendoLeer Iron Man vs.Emprendedor el ...,NaN
4,1255632084313440261,2020-04-29 22:56:32+00:00,yurmailof,Si el corte inglés pone algo a un precio alto ...,NaN
5,1255626420551737345,2020-04-29 22:34:01+00:00,jarfaiterbot,de robajas en el corte inglés,NaN
6,1255621645655592964,2020-04-29 22:15:03+00:00,alber1983can,Jajajaja pero esas reglas no se pueden cambiar...,NaN
7,1255618350375473153,2020-04-29 22:01:57+00:00,nomepidas,La patronal de El Corte Inglés o Ikea apuesta ...,NaN
8,1255617468263018496,2020-04-29 21:58:27+00:00,jonalde,El famoso marketing con corazón... El Corte In...,NaN
9,1255616969417637890,2020-04-29 21:56:28+00:00,Beacanarias,@elcorteinglesac aquí ni te llaman....un pedid...,NaN

In [64]:
tweets.columns=['id_text','created_at_tweet','name_account','text','geo']
tweets

,id_text,created_at_tweet,name_account,text,geo
0,1255640710847401985,2020-04-29 23:30:48+00:00,camilaperezv13,yo nunca lo he hecho en el corte inglés JAJAJA...,NaN
1,1255636516111560706,2020-04-29 23:14:08+00:00,VicenteToms14,O q de n sair a rua bb n haha eu aguento me na...,NaN
2,1255633358748553216,2020-04-29 23:01:35+00:00,Marina47083380,@pablocasado_ @PSOE @podemos @sanchezcastejon ...,NaN
3,1255632958758752257,2020-04-29 23:00:00+00:00,ainderlab,Lo #RecomiendoLeer Iron Man vs.Emprendedor el ...,NaN
4,1255632084313440261,2020-04-29 22:56:32+00:00,yurmailof,Si el corte inglés pone algo a un precio alto ...,NaN
...,...,...,...,...,...
10084,1212164424074768387,2020-01-01 00:11:34+00:00,monchocolatina,¿Las señoras de Baccara trabajaban en El Corte...,NaN
10085,1212164223180115969,2020-01-01 00:10:46+00:00,mikelthekid2152,Pero donde me vas con el traje de currar en el...,NaN
10086,1212162258412982273,2020-01-01 00:02:57+00:00,Manasav_ES,Vestido de mujer Morgan con hebilla y cinturn...,NaN
10087,1212162024576364550,2020-01-01 00:02:02+00:00,Amiguidetrapo,Ya es primavera en el Corte Inglés. #Feliz2020...,NaN
10088,1212161516503523329,2020-01-01 00:00:01+00:00,ainderlab,Lo #RecomiendoLeer Iron Man vs.Emprendedor el ...,NaN

 # Lectura Información Following

In [63]:
def read_Following(file):
    df_following=readCSV(df_id,file)
    df = pd.DataFrame(df_following)
    return df

following = read_Following('followings_info_el_corte_ingles.csv')
following

,id,name,screen_name,created_at,location,followers_count,friends_count,description
0,940274906025091073,Javier Perez Pallares #Neumologia,jpallaresneumo,2017-12-11 17:39:41,"Cartagena, España",1838,817,#Neumologia. Interventional pulmonology. Vicep...
1,2236669338,Pedro Mozas Rello,pedromozasrello,2013-12-08 22:39:01,Madrid,289,354,"Publicista, escritor, guionista, blogger. Miem..."
2,570041347,Ana de Armas,Ana_d_Armas,2012-05-03 14:59:50,NaN,234773,448,Artist.
3,1041739380455624704,alba reche,_albxreche,2018-09-17 17:23:17,España,203015,293,quimera https://t.co/YL3CeV0U9L
4,182764833,Metro de Madrid,metro_madrid,2010-08-25 10:18:32,"Madrid, España",561146,532,Metro de Madrid es la empresa pública que gest...
...,...,...,...,...,...,...,...,...
1609,16293385,Doblecero,webdoblecero,2008-09-15 08:02:35,España,1183,1749,Sé el primero en enterarte de lo que más te in...
1610,164228101,ambitocultural,ambitocultural,2010-07-08 10:34:26,España,10738,2231,Ámbito Cultural de El Corte Inglés promueve la...
1611,414886496,Espacio de Clásica,espacioclasica,2011-11-17 16:27:03,NaN,2140,1081,"Disfruta de conciertos, autores, óperas, y pie..."
1612,207536155,Espacio Indie,espacioindie,2010-10-25 14:28:57,NaN,4803,2578,Nos gusta la música. Hablar de ella. Compartir...
1613,399520547,Espacio de Libros,espaciodelibros,2011-10-27 16:33:38,España,11760,1234,Descubre con Espacio de Libros de @elcorteingl...

In [65]:
following.columns=['id_account','name_account','screen_name_account','created_at_account','location_account','followers_account','friends_account','description_account']
following

,id_account,name_account,screen_name_account,created_at_account,location_account,followers_account,friends_account,description_account
0,940274906025091073,Javier Perez Pallares #Neumologia,jpallaresneumo,2017-12-11 17:39:41,"Cartagena, España",1838,817,#Neumologia. Interventional pulmonology. Vicep...
1,2236669338,Pedro Mozas Rello,pedromozasrello,2013-12-08 22:39:01,Madrid,289,354,"Publicista, escritor, guionista, blogger. Miem..."
2,570041347,Ana de Armas,Ana_d_Armas,2012-05-03 14:59:50,NaN,234773,448,Artist.
3,1041739380455624704,alba reche,_albxreche,2018-09-17 17:23:17,España,203015,293,quimera https://t.co/YL3CeV0U9L
4,182764833,Metro de Madrid,metro_madrid,2010-08-25 10:18:32,"Madrid, España",561146,532,Metro de Madrid es la empresa pública que gest...
...,...,...,...,...,...,...,...,...
1609,16293385,Doblecero,webdoblecero,2008-09-15 08:02:35,España,1183,1749,Sé el primero en enterarte de lo que más te in...
1610,164228101,ambitocultural,ambitocultural,2010-07-08 10:34:26,España,10738,2231,Ámbito Cultural de El Corte Inglés promueve la...
1611,414886496,Espacio de Clásica,espacioclasica,2011-11-17 16:27:03,NaN,2140,1081,"Disfruta de conciertos, autores, óperas, y pie..."
1612,207536155,Espacio Indie,espacioindie,2010-10-25 14:28:57,NaN,4803,2578,Nos gusta la música. Hablar de ella. Compartir...
1613,399520547,Espacio de Libros,espaciodelibros,2011-10-27 16:33:38,España,11760,1234,Descubre con Espacio de Libros de @elcorteingl...

# Modelling Data

In [66]:
#Cruce de tablas para construir el tablón final con la información

fact_following=pd.merge(tweets, following,on=['name_account'],how='inner')
fact_following

,id_text,created_at_tweet,name_account,text,geo,id_account,screen_name_account,created_at_account,location_account,followers_account,friends_account,description_account
0,1254817730651439104,2020-04-27 17:00:35+00:00,CincoDiascom,Visto bueno a la adquisición de Informática El...,NaN,36397274,CincoDiascom,2009-04-29 16:19:02,Madrid,348349,537,"Twitter oficial de Cinco Días, decano de la pr..."
1,1253294762209300480,2020-04-23 12:08:51+00:00,Sportown,"Hazte con las Nike Blazer Mid '77, una de las ...",NaN,229824081,Sportown,2010-12-23 12:32:12,España,1048,835,"Amantes de las 'sneakers', ofrecemos las últim..."
2,1252937797222219776,2020-04-22 12:30:23+00:00,Sportown,La tecnología de ASICS se pone a tu servicio c...,NaN,229824081,Sportown,2010-12-23 12:32:12,España,1048,835,"Amantes de las 'sneakers', ofrecemos las últim..."
3,1263067709815865344,2020-05-20 11:23:03+00:00,RetailerSpain,#RetailVintage Para los nostálgicos... El Cort...,NaN,2614262096,RetailerSpain,2014-07-09 21:38:20,NaN,2540,1624,¿Nos sigues en la aventura del #Retail ?#WeLov...
4,1257380435224662017,2020-05-04 18:43:51+00:00,RetailerSpain,El Corte Inglés de Marineda City cierra y podr...,NaN,2614262096,RetailerSpain,2014-07-09 21:38:20,NaN,2540,1624,¿Nos sigues en la aventura del #Retail ?#WeLov...
5,1231883547486674944,2020-02-24 10:08:19+00:00,RetailerSpain,El Corte Inglés: demanda de 180 millones de eu...,NaN,2614262096,RetailerSpain,2014-07-09 21:38:20,NaN,2540,1624,¿Nos sigues en la aventura del #Retail ?#WeLov...
6,1229733232402411521,2020-02-18 11:43:44+00:00,RetailerSpain,El Corte Inglés redecora sus centros junto a 3...,NaN,2614262096,RetailerSpain,2014-07-09 21:38:20,NaN,2540,1624,¿Nos sigues en la aventura del #Retail ?#WeLov...
7,1229732772979314689,2020-02-18 11:41:55+00:00,RetailerSpain,El Corte Inglés quiere atraer nuevos clientes ...,NaN,2614262096,RetailerSpain,2014-07-09 21:38:20,NaN,2540,1624,¿Nos sigues en la aventura del #Retail ?#WeLov...
8,1228284500108595201,2020-02-14 11:46:59+00:00,RetailerSpain,El Corte Inglés podría reducir su deuda casi u...,NaN,2614262096,RetailerSpain,2014-07-09 21:38:20,NaN,2540,1624,¿Nos sigues en la aventura del #Retail ?#WeLov...
9,1238524881525977088,2020-03-13 17:58:37+00:00,RetailerSpain,El Corte Inglés activa un plan de crisis ante ...,NaN,2614262096,RetailerSpain,2014-07-09 21:38:20,NaN,2540,1624,¿Nos sigues en la aventura del #Retail ?#WeLov...
10,1238524825464954880,2020-03-13 17:58:23+00:00,RetailerSpain,El Corte Inglés cierra sus centros y manda a c...,NaN,2614262096,RetailerSpain,2014-07-09 21:38:20,NaN,2540,1624,¿Nos sigues en la aventura del #Retail ?#WeLov...
11,1234792709874999296,2020-03-03 10:48:18+00:00,RetailerSpain,Renatta&Go traza una nueva hoja de ruta: da un...,NaN,2614262096,RetailerSpain,2014-07-09 21:38:20,NaN,2540,1624,¿Nos sigues en la aventura del #Retail ?#WeLov...
12,1220306418424786952,2020-01-23 11:24:57+00:00,RetailerSpain,Mapa: los centros comerciales que entran en el...,NaN,2614262096,RetailerSpain,2014-07-09 21:38:20,NaN,2540,1624,¿Nos sigues en la aventura del #Retail ?#WeLov...
13,1219963471724453888,2020-01-22 12:42:12+00:00,RetailerSpain,Del Pozo releva a Nuño de la Rosa al frente de...,NaN,2614262096,RetailerSpain,2014-07-09 21:38:20,NaN,2540,1624,¿Nos sigues en la aventura del #Retail ?#WeLov...
14,1219961904598323201,2020-01-22 12:35:58+00:00,RetailerSpain,El Corte Inglés estudia cerrar su centro en Se...,NaN,2614262096,RetailerSpain,2014-07-09 21:38:20,NaN,2540,1624,¿Nos sigues en la aventura del #Retail ?#WeLov...
15,1219908746932936709,2020-01-22 09:04:44+00:00,RetailerSpain,"Plan histórico de El Corte Inglés para cerrar,...",NaN,2614262096,RetailerSpain,2014-07-09 21:38:20,NaN,2540,1624,¿Nos sigues en la aventura del #Retail ?#WeLov...
16,1219238148468891648,2020-01-20 12:40:01+00:00,RetailerSpain,El ocaso de Hipercor: la próxima marca de El C...,NaN,2614262096,RetailerSpain,2014-07-09 21:38:20,NaN,2540,1624,¿Nos sigues en la aventura del #Retail ?#WeLov...
17,1217044769450401793,2020-01-14 11:24:19+00:00,RetailerSpain,El Corte Inglés desplaza a Hipercor en su est...,NaN,2614262096,RetailerSpain,2014-07-09 21:38:20,NaN,2540,1624,¿Nos sigues en la aventura del #Retail ?#WeLov...
18,1216661758875664384,2020-01-13 10:02:22+00:00,RetailerSpain,El Corte Inglés pide autorización al BdE para ...,NaN,2614262096,RetailerSpain,2014-07-09 21:38:20,NaN,2540,1624,¿Nos sigues en la aventura del #Retail ?#WeLov...
19,1216661400782802944,2020-01-13 10:00:57+00:00,RetailerSpain,La filial inmobiliaria de El Corte Inglés aume...,NaN,2614262096,RetailerSpain,2014-07-09 21:38:20,NaN,2540,1624,¿Nos sigues en la aventura del #Retail ?#WeLov...
20,1216661318624776192,2020-01-13 10:00:37+00:00,RetailerSpain,Repsol y El Corte Inglés abren casi un Superco...,NaN,2614262096,RetailerSpain,2014-07-09 21:38:20,NaN,2540,1624,¿Nos sigues en la aventura del #Retail ?#WeLov...
21,1213023990337490944,2020-01-03 09:07:10+00:00,RetailerSpain,La rebelión de los juguetes contra Amazon: Toy...,NaN,2614262096,RetailerSpain,2014-07-09 21:38:20,NaN,2540,1624,¿Nos sigues en la aventura del #Retail ?#WeLov...
22,1212702531555659777,2020-01-02 11:49:49+00:00,RetailerSpain,El Corte Inglés despeja su futuro con el adió...,NaN,2614262096,RetailerSpain,2014-07-09 21:38:20,NaN,2540,1624,¿Nos sigues en la aventura del #Retail ?#WeLov...
23,1260984978181099522,2020-05-14 17:27:01+00:00,Dyson,¡Hola! En este caso deberías hablar con El Cor...,NaN,1410302630,Dyson,2013-05-07 13:52:50,NaN,69362,879,We’re here to share news and updates about Dys...
24,1259740548396650499,2020-05-11 07:02:06+00:00,xataka,Las 16 mejores ofertas de la semana de Interne...,NaN,18200400,xataka,2008-12-17 21:28:48,España y Latinoamérica,1403635,43,Xataka es la publicación líder de tecnología e...
25,1240294803050573824,2020-03-18 15:11:39+00:00,xataka,Comprar por Internet en tiempos de Coronavirus...,NaN,18200400,xataka,2008-12-17 21:28:48,España y Latinoamérica,1403635,43,Xataka es la publicación líder de tecnología e...
26,1222986156679278593,2020-01-30 20:53:16+00:00,xataka,"Carolina Prieto, directora general de Motorola...",NaN,18200400,xataka,2008-12-17 21:28:48,España y Latinoamérica,1403635,43,Xataka es la publicación líder de tecnología e...
27,1218104446636392449,2020-01-17 09:35:06+00:00,xataka,"Xiaomi Mi Scooter Pro, iPhone XR y Redmi Note ...",NaN,18200400,xataka,2008-12-17 21:28:48,España y Latinoamérica,1403635,43,Xataka es la publicación líder de tecnología e...
28,1218040257154818052,2020-01-17 05:20:02+00:00,xataka,"¡Estas son las mejores ofertas del ""Día sin IV...",NaN,18200400,xataka,2008-12-17 21:28:48,España y Latinoamérica,1403635,43,Xataka es la publicación líder de tecnología e...
29,1218010057826238464,2020-01-17 03:20:01+00:00,xataka,Arrancan en El Corte Inglés 48 horas de descue...,NaN,18200400,xataka,2008-12-17 21:28:48,España y Latinoamérica,1403635,43,Xataka es la publicación líder de tecnología e...
30,1217916963982323723,2020-01-16 21:10:06+00:00,xataka,"Las mejores ofertas del ""Día sin IVA"" de El Co...",NaN,18200400,xataka,2008-12-17 21:28:48,España y Latinoamérica,1403635,43,Xataka es la publicación líder de tecnología e...
31,1217812522771931141,2020-01-16 14:15:05+00:00,xataka,Arrancan en El Corte Inglés 48 horas de descue...,NaN,18200400,xataka,2008-12-17 21:28:48,España y Latinoamérica,1403635,43,Xataka es la publicación líder de tecnología e...
32,1212564172808040448,2020-01-02 02:40:01+00:00,xataka,"Qué es MyInvestor, el neobanco en que El Corte...",NaN,18200400,xataka,2008-12-17 21:28:48,España y Latinoamérica,1403635,43,Xataka es la publicación líder de tecnología e...
33,1212455976093339650,2020-01-01 19:30:05+00:00,xataka,"Qué es MyInvestor, el neobanco en que El Corte...",NaN,18200400,xataka,2008-12-17 21:28:48,España y Latinoamérica,1403635,43,Xataka es la publicación líder de tecnología e...
34,1232599152137265152,2020-02-26 09:31:53+00:00,Biotherm_es,"Alerta #BiothermLovers, ¡Ha aparecido un iceb...",NaN,1241217090,Biotherm_es,2013-03-04 12:20:21,Atención al cliente: 900813131,5430,332,Bienvenid@ a la comunidad de los #BiothermLove...
35,1227936981130317830,2020-02-13 12:46:04+00:00,KiehlsSpain,¿Estás buscando el regalo perfecto para este S...,NaN,47100724,KiehlsSpain,2009-06-14 14:32:22,Spain,18197,372,Kiehl’s es una empresa cosmética que nace como...
36,1242155509186211841,2020-03-23 18:25:26+00:00,CarlosOnRetail,"In Spain, @elcorteingles is prioritising groce...",NaN,2183187386,CarlosOnRetail,2013-11-08 23:24:37,Madrid,1177,653,"Retail Analyst analysing the Spanish, Portugue..."
37,1237806657855504390,2020-03-11 18:24:39+00:00,CarlosOnRetail,"Despite #COVID19 worrying news, it is business...",NaN,2183187386,CarlosOnRetail,2013-11-08 23:24:37,Madrid,1177,653,"Retail Analyst analysing the Spanish, Portugue..."
38,1237716742409007104,2020-03-11 12:27:21+00:00,chicadelatele,El supermercado de El Corte Inglés también,NaN,4473901,chicadelatele,2007-04-13 08:53:35,NaN,6904,184,"No soy periodista y solo hago opinión, persona..."
39,1221789310325809152,2020-01-27 13:37:25+00:00,CharHadas,The Petite Special Day será el momento perfect...,NaN,106386077,CharHadas,2010-01-19 11:36:40,Spain,13045,833,"Únete a nuestra Red Social de Madres. Moda, A..."
40,1218468896031809536,2020-01-18 09:43:17+00:00,ambitocultural,"No es necesario, con presentarse algo antes de...",NaN,164228101,ambitocultural,2010-07-08 10:34:26,España,10738,2231,Ámbito Cultural de El Corte Inglés promueve la...
41,1218150263846055936,2020-01-17 12:37:09+00:00,ambitocultural,Tan sólo llegar algo antes de la hora! Sala Am...,NaN,164228101,ambitocultural,2010-07-08 10:34:26,España,10738,2231,Ámbito Cultural de El Corte Inglés promueve la...
42,1217368746974752769,2020-01-15 08:51:41+00:00,ambitocultural,Hola! Puedes visitarla en el horario normal de...,NaN,164228101,ambitocultural,2010-07-08 10:34:26,España,10738,2231,Ámbito Cultural de El Corte Inglés promueve la...

In [16]:
fact_following.sort_values(by=['id_account','created_at_tweet'])

Empty DataFrame
Columns: [id_account, name_account, screen_name_account, created_at_account, location_account, followers_account, friends_account, description_account, created_at_tweet, id_str, text]
Index: []