In [3]:
import pandas as pd

In [10]:
#Definci칩n de variables
df_id = pd.DataFrame()
df_info = pd.DataFrame()
df_tweets = pd.DataFrame()
fact_following = pd.DataFrame()

In [11]:
#Lectura en ficheros de los IDS de Twitter
def readID(dataframe,file):
    dataframe = pd.read_csv(file,sep=',')
    return dataframe

following_ids=readID(df_id,'followings_id.csv')
following_ids

     Unnamed: 0            id_Cuenta
0             0             48422383
1             1  1173984355800293377
2             2           2992924523
3             3   715535722086801408
4             4   906103502841290752
..          ...                  ...
626         626             20332892
627         627             92256751
628         628             29163531
629         629             16777682
630         630             50615281

[631 rows x 2 columns]

In [12]:
#Lectura en ficheros de los IDS de Twitter
def readInfo(dataframe,file):
    dataframe = pd.read_csv(file,sep=',')
    return dataframe


df_following_info=readID(df_info,'followings_info.csv')
df_following_info

,Unnamed: 0,id,name,screen_name,created_at,location,followers_count,friends_count,description
0,0,48422383,Jonathan Chac칩n,jonathanchacon,2009-06-18 17:29:37,Transitando por el 游깴,2468,233,Senior accessibility software engineer at @Cab...
1,1,1173984355800293377,Mobilidade Coru침esa,MobilidadeC,2019-09-17 15:37:47,NaN,1,6,"Ideas, proxectos, actualidade e noticias sobre..."
2,2,2992924523,Cabify,cabify,2015-01-22 20:30:57,Global,2156,26,We want to make cities better places to live.\...
3,3,715535722086801408,Mutua Madrile침a,la_Mutua,2016-03-31 13:46:24,NaN,4856,312,#JuntosEvolucionamos hacia todo lo que est치 po...
4,4,906103502841290752,Movilidad Sostenible,MadridSummitMS,2017-09-08 10:34:44,"Madrid, Comunidad de Madrid",550,269,Impulsando la Movilidad Sostenible desde las e...
...,...,...,...,...,...,...,...,...,...
94,94,105855492,Miguel Justribo,migueljustribo,2010-01-17 18:32:56,madrid,1502,1530,"Zaragozano, Atl칠tico, contador de historias, c..."
95,95,28991317,Jessica Moll치,llesay,2009-04-05 14:01:16,"Madrid, Comunidad de Madrid",1272,608,Since 1983. Representante de actores en @mesal...
96,96,239965125,MANU ORTIZ游눞,ManuOrtiz22,2011-01-18 21:12:33,Madrid,1414,813,#Productor #Redactor. Paseando por @Tve_tve de...
97,97,421814594,Mikel Iglesias,Mikelino10,2011-11-26 12:16:25,mikel@cactusproduccio.com,79247,461,21. 游꿘游꿗游꿟 Actualmente ''El Perla'' en ''Perd칩nam...
98,98,3082828152,FCoC 游끦 #SensorialSquad,FernandoCoCYT,2015-03-15 00:17:58,Valladolid,48673,380,RECULA RECULA!!. +700k. #SensorialSquad #Fersk...

In [13]:
#Lectura en ficheros de los IDS de Twitter
def readTweest(dataframe,file):
    dataframe = pd.read_csv(file,sep=',')
    return dataframe


df_following_info_tweets=readID(df_tweets,'followings_info_tweets.csv')
df_following_info_tweets

,Unnamed: 0,id_tweet,id_user,text,location,created_at
0,0,1218263281833476096,48422383,RT @saucelabs: The dynamic duo of @helenedoume...,Transitando por el 游깴,2020-01-17 20:06:15
1,1,1217846135424999426,48422383,RT @saucelabs: Let's get to know some of our s...,Transitando por el 游깴,2020-01-16 16:28:39
2,2,1216732618890403842,2992924523,Un inspirador an치lisis realizado por @sifted e...,Global,2020-01-13 14:43:56
3,3,1214864392745037824,2992924523,"@locolive76 @DNDConsumidor Hola, G@By: lamenta...",Global,2020-01-08 11:00:16

In [16]:
#Cruce de tablas para construir el tabl칩n final con la informaci칩n

fact_following=pd.merge(df_following_info, df_following_info_tweets, how='left',
                       left_on=['id'], 
                       right_on=['id_user'])
fact_following

,Unnamed: 0_x,id,name,screen_name,created_at_x,location_x,followers_count,friends_count,description,Unnamed: 0_y,id_tweet,id_user,text,location_y,created_at_y
0,0,48422383,Jonathan Chac칩n,jonathanchacon,2009-06-18 17:29:37,Transitando por el 游깴,2468,233,Senior accessibility software engineer at @Cab...,0.0,1.218263e+18,4.842238e+07,RT @saucelabs: The dynamic duo of @helenedoume...,Transitando por el 游깴,2020-01-17 20:06:15
1,0,48422383,Jonathan Chac칩n,jonathanchacon,2009-06-18 17:29:37,Transitando por el 游깴,2468,233,Senior accessibility software engineer at @Cab...,1.0,1.217846e+18,4.842238e+07,RT @saucelabs: Let's get to know some of our s...,Transitando por el 游깴,2020-01-16 16:28:39
2,1,1173984355800293377,Mobilidade Coru침esa,MobilidadeC,2019-09-17 15:37:47,NaN,1,6,"Ideas, proxectos, actualidade e noticias sobre...",NaN,NaN,NaN,NaN,NaN,NaN
3,2,2992924523,Cabify,cabify,2015-01-22 20:30:57,Global,2156,26,We want to make cities better places to live.\...,2.0,1.216733e+18,2.992925e+09,Un inspirador an치lisis realizado por @sifted e...,Global,2020-01-13 14:43:56
4,2,2992924523,Cabify,cabify,2015-01-22 20:30:57,Global,2156,26,We want to make cities better places to live.\...,3.0,1.214864e+18,2.992925e+09,"@locolive76 @DNDConsumidor Hola, G@By: lamenta...",Global,2020-01-08 11:00:16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,94,105855492,Miguel Justribo,migueljustribo,2010-01-17 18:32:56,madrid,1502,1530,"Zaragozano, Atl칠tico, contador de historias, c...",NaN,NaN,NaN,NaN,NaN,NaN
97,95,28991317,Jessica Moll치,llesay,2009-04-05 14:01:16,"Madrid, Comunidad de Madrid",1272,608,Since 1983. Representante de actores en @mesal...,NaN,NaN,NaN,NaN,NaN,NaN
98,96,239965125,MANU ORTIZ游눞,ManuOrtiz22,2011-01-18 21:12:33,Madrid,1414,813,#Productor #Redactor. Paseando por @Tve_tve de...,NaN,NaN,NaN,NaN,NaN,NaN
99,97,421814594,Mikel Iglesias,Mikelino10,2011-11-26 12:16:25,mikel@cactusproduccio.com,79247,461,21. 游꿘游꿗游꿟 Actualmente ''El Perla'' en ''Perd칩nam...,NaN,NaN,NaN,NaN,NaN,NaN
100,98,3082828152,FCoC 游끦 #SensorialSquad,FernandoCoCYT,2015-03-15 00:17:58,Valladolid,48673,380,RECULA RECULA!!. +700k. #SensorialSquad #Fersk...,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
p=fact_following['id'=='48422383']

KeyError: False